name: Set "End date" property when project card moved to Done

on:
  project_card:
    types: 
      - moved
  
jobs:
  set_done_date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context.payload);
