# When an issue is closed, set the end date to the current date on the related project card.
name: Set Done Date

on:
  issues:
    types: [closed]

jobs:
  set_done_date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Log the event payload
            // console.log(JSON.stringify(context.payload, null, 2));

            // Get issue number from the event payload
            const issueNumber = context.payload.issue.number;

            // Get the issue
            const { data: issue } = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });

            // Log the issue
            console.log(JSON.stringify(issue, null, 2));